server:
  port: 8015
spring:
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.189:3306/master?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false&autoReconnect=true
    slave1:
      type: com.alibaba.druid.pool.DruidDataSource
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.189:3306/slave1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false&autoReconnect=true
    slave2:
      type: com.alibaba.druid.pool.DruidDataSource
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.189:3306/slave2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false&autoReconnect=true
  application:
    name: dynamicDataSource-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# 逻辑删除：需要在字段上加@TableLogic注解，还需要配置一下@bean
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0