server:
  port: 8991
spring:
  redis:
    port: 6379
    host: 127.0.0.1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.189:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false&autoReconnect=true
    password: root
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: auth-center
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.ksn.entity.**